from datetime import UTC, date, datetime
from sqlalchemy import Date, DateTime, Float, ForeignKey, Index, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from .database import Base

class TS:
    created_at: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(UTC))
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(UTC), onupdate=lambda: datetime.now(UTC))

class Engagement(Base, TS):
    __tablename__="engagements"
    id: Mapped[int]=mapped_column(primary_key=True); company_name: Mapped[str]=mapped_column(String(180),index=True); industry: Mapped[str]=mapped_column(String(60),index=True)
    country: Mapped[str]=mapped_column(String(80),default="United Kingdom"); employees: Mapped[int]=mapped_column(Integer); annual_revenue: Mapped[float]=mapped_column(Float); operating_cost: Mapped[float]=mapped_column(Float)
    strategic_objectives: Mapped[str]=mapped_column(Text,default=""); current_challenges: Mapped[str]=mapped_column(Text,default=""); diagnostic_period: Mapped[str]=mapped_column(String(80),default="Last 12 months")
    primary_stakeholder: Mapped[str]=mapped_column(String(120),default="Executive sponsor"); status: Mapped[str]=mapped_column(String(30),default="Active",index=True)
    assessments=relationship("FunctionalAssessment",cascade="all, delete-orphan"); findings=relationship("Finding",cascade="all, delete-orphan"); opportunities=relationship("Opportunity",cascade="all, delete-orphan")

class CompanyProfile(Base, TS):
    __tablename__="company_profiles"; id: Mapped[int]=mapped_column(primary_key=True); engagement_id: Mapped[int]=mapped_column(ForeignKey("engagements.id",ondelete="CASCADE"),unique=True,index=True)
    business_model: Mapped[str]=mapped_column(Text,default=""); locations: Mapped[int]=mapped_column(Integer,default=1); channels: Mapped[str]=mapped_column(Text,default=""); context_notes: Mapped[str]=mapped_column(Text,default="")

class FunctionalAssessment(Base, TS):
    __tablename__="functional_assessments"; id: Mapped[int]=mapped_column(primary_key=True); engagement_id: Mapped[int]=mapped_column(ForeignKey("engagements.id",ondelete="CASCADE"),index=True); function: Mapped[str]=mapped_column(String(80),index=True)
    maturity: Mapped[int]=mapped_column(Integer); importance: Mapped[int]=mapped_column(Integer); performance_score: Mapped[int]=mapped_column(Integer); evidence: Mapped[str]=mapped_column(Text,default=""); pain_points: Mapped[str]=mapped_column(Text,default=""); kpis: Mapped[str]=mapped_column(Text,default="")
    manual_processes: Mapped[str]=mapped_column(Text,default=""); systems_used: Mapped[str]=mapped_column(Text,default=""); data_quality: Mapped[int]=mapped_column(Integer,default=3); employee_feedback: Mapped[str]=mapped_column(Text,default=""); customer_impact: Mapped[str]=mapped_column(Text,default="")
    __table_args__=(Index("ix_assessment_engagement_function","engagement_id","function",unique=True),)

class DatasetUpload(Base, TS):
    __tablename__="dataset_uploads"; id: Mapped[int]=mapped_column(primary_key=True); engagement_id: Mapped[int]=mapped_column(ForeignKey("engagements.id",ondelete="CASCADE"),index=True); dataset_type: Mapped[str]=mapped_column(String(50),index=True); original_filename: Mapped[str]=mapped_column(String(255)); stored_filename: Mapped[str]=mapped_column(String(255)); row_count: Mapped[int]=mapped_column(Integer,default=0); status: Mapped[str]=mapped_column(String(30),default="pending")
class DataQualityIssue(Base, TS):
    __tablename__="data_quality_issues"; id: Mapped[int]=mapped_column(primary_key=True); upload_id: Mapped[int]=mapped_column(ForeignKey("dataset_uploads.id",ondelete="CASCADE"),index=True); severity: Mapped[str]=mapped_column(String(20),index=True); issue_type: Mapped[str]=mapped_column(String(50)); column_name: Mapped[str|None]=mapped_column(String(120),nullable=True); row_number: Mapped[int|None]=mapped_column(Integer,nullable=True); message: Mapped[str]=mapped_column(Text)
class KPI(Base, TS):
    __tablename__="kpis"; id: Mapped[int]=mapped_column(primary_key=True); engagement_id: Mapped[int]=mapped_column(ForeignKey("engagements.id",ondelete="CASCADE"),index=True); function: Mapped[str]=mapped_column(String(60),index=True); name: Mapped[str]=mapped_column(String(120),index=True); period: Mapped[str]=mapped_column(String(30)); value: Mapped[float]=mapped_column(Float); target: Mapped[float|None]=mapped_column(Float,nullable=True); unit: Mapped[str]=mapped_column(String(20),default="%"); source: Mapped[str]=mapped_column(String(200),default="Uploaded dataset")
class Finding(Base, TS):
    __tablename__="findings"; id: Mapped[int]=mapped_column(primary_key=True); engagement_id: Mapped[int]=mapped_column(ForeignKey("engagements.id",ondelete="CASCADE"),index=True); title: Mapped[str]=mapped_column(String(200)); function: Mapped[str]=mapped_column(String(60),index=True); statement: Mapped[str]=mapped_column(Text); evidence: Mapped[str]=mapped_column(Text); affected_kpi: Mapped[str]=mapped_column(String(120)); severity: Mapped[int]=mapped_column(Integer); urgency: Mapped[int]=mapped_column(Integer); confidence: Mapped[int]=mapped_column(Integer); finding_type: Mapped[str]=mapped_column(String(40),default="likely finding"); annual_impact: Mapped[float]=mapped_column(Float,default=0); stakeholders: Mapped[str]=mapped_column(Text,default="")
class Hypothesis(Base, TS):
    __tablename__="hypotheses"; id: Mapped[int]=mapped_column(primary_key=True); finding_id: Mapped[int]=mapped_column(ForeignKey("findings.id",ondelete="CASCADE"),index=True); statement: Mapped[str]=mapped_column(Text); evidence_for: Mapped[str]=mapped_column(Text,default=""); evidence_against: Mapped[str]=mapped_column(Text,default=""); confidence: Mapped[int]=mapped_column(Integer,default=50); validation_action: Mapped[str]=mapped_column(Text,default="")
class RootCause(Base, TS):
    __tablename__="root_causes"; id: Mapped[int]=mapped_column(primary_key=True); finding_id: Mapped[int]=mapped_column(ForeignKey("findings.id",ondelete="CASCADE"),index=True); observed_symptom: Mapped[str]=mapped_column(Text); possible_causes: Mapped[str]=mapped_column(Text); evidence_for: Mapped[str]=mapped_column(Text); evidence_against: Mapped[str]=mapped_column(Text,default=""); confidence: Mapped[int]=mapped_column(Integer); validation_action: Mapped[str]=mapped_column(Text); final_root_cause: Mapped[str]=mapped_column(Text); method: Mapped[str]=mapped_column(String(80),default="People–Process–Technology–Data")
class Opportunity(Base, TS):
    __tablename__="opportunities"; id: Mapped[int]=mapped_column(primary_key=True); engagement_id: Mapped[int]=mapped_column(ForeignKey("engagements.id",ondelete="CASCADE"),index=True); finding_id: Mapped[int|None]=mapped_column(ForeignKey("findings.id",ondelete="SET NULL"),nullable=True); title: Mapped[str]=mapped_column(String(200)); category: Mapped[str]=mapped_column(String(80),index=True); description: Mapped[str]=mapped_column(Text); intervention: Mapped[str]=mapped_column(Text); annual_benefit: Mapped[float]=mapped_column(Float); initial_cost: Mapped[float]=mapped_column(Float); recurring_cost: Mapped[float]=mapped_column(Float,default=0); duration_months: Mapped[int]=mapped_column(Integer); difficulty: Mapped[int]=mapped_column(Integer); readiness: Mapped[int]=mapped_column(Integer); alignment: Mapped[int]=mapped_column(Integer); impact: Mapped[int]=mapped_column(Integer); feasibility: Mapped[int]=mapped_column(Integer); time_to_value: Mapped[int]=mapped_column(Integer); risk: Mapped[int]=mapped_column(Integer); dependencies: Mapped[str]=mapped_column(Text,default=""); major_risks: Mapped[str]=mapped_column(Text,default=""); success_metrics: Mapped[str]=mapped_column(Text,default=""); priority_score: Mapped[float]=mapped_column(Float,default=0); classification: Mapped[str]=mapped_column(String(40),default="Defer")
class Recommendation(Base, TS):
    __tablename__="recommendations"; id: Mapped[int]=mapped_column(primary_key=True); opportunity_id: Mapped[int]=mapped_column(ForeignKey("opportunities.id",ondelete="CASCADE"),index=True); finding: Mapped[str]=mapped_column(Text); evidence: Mapped[str]=mapped_column(Text); root_cause: Mapped[str]=mapped_column(Text); recommendation: Mapped[str]=mapped_column(Text); business_impact: Mapped[str]=mapped_column(Text); delivery_approach: Mapped[str]=mapped_column(Text); risks_mitigations: Mapped[str]=mapped_column(Text); success_measures: Mapped[str]=mapped_column(Text)
class RoadmapInitiative(Base, TS):
    __tablename__="roadmap_initiatives"; id: Mapped[int]=mapped_column(primary_key=True); engagement_id: Mapped[int]=mapped_column(ForeignKey("engagements.id",ondelete="CASCADE"),index=True); opportunity_id: Mapped[int|None]=mapped_column(ForeignKey("opportunities.id",ondelete="SET NULL"),nullable=True); title: Mapped[str]=mapped_column(String(200)); phase: Mapped[str]=mapped_column(String(60)); owner: Mapped[str]=mapped_column(String(120)); start_month: Mapped[int]=mapped_column(Integer); end_month: Mapped[int]=mapped_column(Integer); milestone: Mapped[str]=mapped_column(Text); dependency: Mapped[str]=mapped_column(Text,default=""); status: Mapped[str]=mapped_column(String(30),default="Not started"); expected_outcome: Mapped[str]=mapped_column(Text); kpi: Mapped[str]=mapped_column(String(160)); decision_gate: Mapped[str]=mapped_column(Text)
class Risk(Base, TS):
    __tablename__="risks"; id: Mapped[int]=mapped_column(primary_key=True); engagement_id: Mapped[int]=mapped_column(ForeignKey("engagements.id",ondelete="CASCADE"),index=True); description: Mapped[str]=mapped_column(Text); category: Mapped[str]=mapped_column(String(60),index=True); likelihood: Mapped[int]=mapped_column(Integer); impact: Mapped[int]=mapped_column(Integer); overall_rating: Mapped[int]=mapped_column(Integer); mitigation: Mapped[str]=mapped_column(Text); contingency: Mapped[str]=mapped_column(Text); owner: Mapped[str]=mapped_column(String(120)); review_date: Mapped[date]=mapped_column(Date); status: Mapped[str]=mapped_column(String(30),default="Open")
class Stakeholder(Base, TS):
    __tablename__="stakeholders"; id: Mapped[int]=mapped_column(primary_key=True); engagement_id: Mapped[int]=mapped_column(ForeignKey("engagements.id",ondelete="CASCADE"),index=True); name: Mapped[str]=mapped_column(String(120)); role: Mapped[str]=mapped_column(String(120)); influence: Mapped[int]=mapped_column(Integer); interest: Mapped[int]=mapped_column(Integer); current_support: Mapped[int]=mapped_column(Integer); desired_support: Mapped[int]=mapped_column(Integer); concerns: Mapped[str]=mapped_column(Text); engagement_approach: Mapped[str]=mapped_column(Text); communication_frequency: Mapped[str]=mapped_column(String(60)); classification: Mapped[str]=mapped_column(String(40))
class BenefitEstimate(Base, TS):
    __tablename__="benefit_estimates"; id: Mapped[int]=mapped_column(primary_key=True); opportunity_id: Mapped[int]=mapped_column(ForeignKey("opportunities.id",ondelete="CASCADE"),index=True); non_financial_benefit: Mapped[str]=mapped_column(Text); worst_case: Mapped[float]=mapped_column(Float); base_case: Mapped[float]=mapped_column(Float); best_case: Mapped[float]=mapped_column(Float); confidence: Mapped[int]=mapped_column(Integer); assumptions: Mapped[str]=mapped_column(Text)
class AuditEvent(Base):
    __tablename__="audit_events"; id: Mapped[int]=mapped_column(primary_key=True); engagement_id: Mapped[int|None]=mapped_column(ForeignKey("engagements.id",ondelete="SET NULL"),nullable=True,index=True); action: Mapped[str]=mapped_column(String(100),index=True); resource_type: Mapped[str]=mapped_column(String(80)); resource_id: Mapped[int|None]=mapped_column(Integer,nullable=True); detail: Mapped[str]=mapped_column(Text,default=""); created_at: Mapped[datetime]=mapped_column(DateTime,default=lambda: datetime.now(UTC),index=True)
