from datetime import date
from .models import *
from .engines import score_opportunity
FUNCTIONS=["Strategy","Finance","Operations","Sales","Marketing","Customer service","Human resources","Technology","Data and AI","Risk and compliance","Supply chain"]
def seed_demo(db):
    found=db.query(Engagement).filter_by(company_name="NorthStar Retail Ltd").first()
    if found:return found
    e=Engagement(company_name="NorthStar Retail Ltd",industry="retail",country="United Kingdom",employees=620,annual_revenue=48_000_000,operating_cost=45_120_000,strategic_objectives="Restore margin; improve omnichannel availability; build scalable management information",current_challenges="Declining operating margin, delivery delays, stock-outs, rising complaints and fragmented spreadsheet reporting",diagnostic_period="January–December 2025",primary_stakeholder="Chief Operating Officer",status="Active");db.add(e);db.flush()
    db.add(CompanyProfile(engagement_id=e.id,business_model="34-store omnichannel retailer with central warehouse and online channel",locations=35,channels="Stores; e-commerce",context_notes="All financial benefits are indicative base-case estimates and require validation."))
    details={"Operations":(2,5,2,"On-time delivery fell from 91% to 73% while average delay rose from 1.5 to 2.1 days.","Warehouse-to-carrier hand-offs; inconsistent store replenishment"),"Supply chain":(2,5,2,"Stock-out rate averaged 9.8% against a 4% target.","Spreadsheet forecasting; no shared inventory view"),"Data and AI":(1,5,2,"Weekly executive pack requires 96 staff-hours and reconciles 17 spreadsheets.","Manual extraction and inconsistent definitions"),"Customer service":(2,4,2,"Complaints rose from 820 to 1,190 per month; 61% relate to delivery or availability.","Reactive case handling; limited order visibility"),"Finance":(3,5,2,"Operating margin declined from 8.6% to 6.0%.","Cost growth outpaced revenue growth")}
    for f in FUNCTIONS:
        m,i,p,ev,pain=details.get(f,(3,3,3,"Management interview evidence; further validation required.","No material issue confirmed"))
        db.add(FunctionalAssessment(engagement_id=e.id,function=f,maturity=m,importance=i,performance_score=p,evidence=ev,pain_points=pain,kpis="Function-specific scorecard",manual_processes="See evidence log",systems_used="ERP and spreadsheets",data_quality=2 if f in details else 3,employee_feedback="Teams report duplicate data entry",customer_impact="Material" if f in ["Operations","Supply chain","Customer service"] else "Indirect"))
    fs=[("Delivery delays increased 40%","Operations","Average delivery delay increased from 1.5 to 2.1 days (+40%) over the diagnostic period.","Monthly operations dataset: delay 1.5→2.1 days; on-time rate 91%→73%.","On-time completion",5,5,95,"confirmed finding",1_050_000,"Customers; COO; warehouse; carriers"),("Stock availability is below target","Supply chain","Stock-out rate averaged 9.8%, 5.8 percentage points above the 4% target.","Monthly inventory extracts across 34 stores; 9.8% average stock-out rate.","Stock-out rate",5,5,90,"confirmed finding",1_440_000,"Customers; store managers; merchandising"),("Executive reporting consumes excessive effort","Data and AI","Weekly reporting consumes 96 staff-hours and remains prone to reconciliation differences.","Process observation: 17 spreadsheets, 96 hours per weekly cycle.","Reporting effort",4,4,90,"confirmed finding",310_000,"Executive team; finance analysts"),("Demand forecasting is inconsistent","Supply chain","Store forecasts use different spreadsheet logic, contributing to simultaneous stock-outs and excess stock.","Forecast variance differs materially by store; causal link requires pilot validation.","Forecast accuracy",4,4,70,"likely finding",820_000,"Merchandising; stores; finance"),("Complaints track delivery and availability failures","Customer service","Complaint volumes increased 45%; 61% are tagged delivery or stock availability.","CRM category analysis: 1,190 vs 820 monthly complaints; 61% relevant tags.","Complaint volume",4,5,88,"confirmed finding",390_000,"Customers; service teams; brand lead")]
    findings=[]
    for x in fs:
        f=Finding(engagement_id=e.id,title=x[0],function=x[1],statement=x[2],evidence=x[3],affected_kpi=x[4],severity=x[5],urgency=x[6],confidence=x[7],finding_type=x[8],annual_impact=x[9],stakeholders=x[10]);db.add(f);db.flush();findings.append(f)
        db.add(RootCause(finding_id=f.id,observed_symptom=x[2],possible_causes="People: inconsistent ownership | Process: non-standard hand-offs | Technology: fragmented systems | Data: delayed and inconsistent records",evidence_for=x[3],evidence_against="Seasonality and supplier mix have not been fully controlled",confidence=max(55,x[7]-15),validation_action="Run a four-week controlled pilot and segment outcomes by store, carrier and SKU.",final_root_cause="Fragmented planning and control processes are the leading supported cause; causality remains subject to pilot validation."))
    specs=[("Delivery-performance control tower","system integration",0,1_050_000,280_000,70_000,5,3,4,5,4,4,4,2,"Clean carrier event feeds","Poor scan compliance","On-time delivery ≥90%; delay ≤1.6 days"),("Inventory visibility dashboard","data governance",1,1_440_000,220_000,55_000,4,3,4,5,4,4,4,2,"SKU master-data remediation","Low store adoption","Stock-outs ≤4%; inventory accuracy ≥97%"),("Automated executive reporting","automation",2,310_000,95_000,20_000,3,2,5,4,5,5,5,1,"Agree KPI definitions","Automation of inconsistent definitions","Reporting effort -75%; pack issued by day 3"),("Demand forecasting pilot","AI enablement",3,820_000,190_000,60_000,5,4,3,5,3,3,3,3,"Inventory data and category owner","Model drift and override behaviour","Forecast error -20%; availability +4pp"),("Service recovery workflow","customer-experience improvement",4,390_000,120_000,35_000,3,2,4,4,5,4,5,2,"Order-status integration","Inconsistent case coding","Complaints -25%; FCR +12pp"),("Store process standardisation","process redesign",1,520_000,160_000,30_000,6,3,3,4,4,4,3,2,"Regional manager capacity","Local workarounds persist","Replenishment adherence ≥90%"),("Targeted planner training","workforce training",3,180_000,60_000,10_000,2,1,5,3,5,5,5,1,"Forecast process design","Skills decay","Training completion ≥95%; override quality")]
    for s in specs:
        score,label=score_opportunity({"impact":s[7],"alignment":s[8],"feasibility":s[9],"time_to_value":s[10],"readiness":s[11],"risk":s[12],"cost":s[13],"difficulty":s[6]})
        o=Opportunity(engagement_id=e.id,finding_id=findings[s[2]].id,title=s[0],category=s[1],description=f"Address {findings[s[2]].title.lower()} with a controlled, evidence-led intervention.",intervention=f"Design, pilot and scale {s[0].lower()} with named process owners and decision gates.",annual_benefit=s[3],initial_cost=s[4],recurring_cost=s[5],duration_months=s[6],difficulty=s[7],readiness=s[8],alignment=s[9],impact=s[10],feasibility=s[11],time_to_value=s[11],risk=s[12],dependencies=s[14],major_risks=s[15],success_metrics=s[16],priority_score=score,classification=label);db.add(o);db.flush()
        db.add(BenefitEstimate(opportunity_id=o.id,non_financial_benefit="Improved decision speed and customer reliability",worst_case=s[3]*.6,base_case=s[3],best_case=s[3]*1.25,confidence=70,assumptions="Benefit is gross, annualised and indicative; no overlap adjustment applied."))
        db.add(Recommendation(opportunity_id=o.id,finding=findings[s[2]].statement,evidence=findings[s[2]].evidence,root_cause="Fragmented process ownership, disconnected data and limited performance control.",recommendation=o.intervention,business_impact=f"Indicative gross annual benefit £{s[3]:,.0f}; initial cost £{s[4]:,.0f}.",delivery_approach="Baseline; design; controlled pilot; decision gate; phased rollout; benefits assurance.",risks_mitigations=f"{s[15]}. Mitigate through data controls, adoption tracking and gated release.",success_measures=s[16]))
        start=1 if label=="Quick Win" else 3 if label=="Strategic Priority" else 5; end=min(12,start+s[6]-1); phase="Phase 1: Diagnose and stabilise" if start<=2 else "Phase 2: Pilot and validate" if start<=4 else "Phase 3: Scale"
        db.add(RoadmapInitiative(engagement_id=e.id,opportunity_id=o.id,title=s[0],phase=phase,owner="Transformation Director",start_month=start,end_month=end,milestone="Pilot outcome reviewed",dependency=s[14],status="Not started",expected_outcome=s[16],kpi=s[16].split(";")[0],decision_gate=f"Proceed only if leading KPI improves by month {min(end,6)}"))
    for desc,cat,l,i,mit in [("Store adoption is insufficient","change management",4,4,"Use store champions and weekly adoption reviews"),("Inventory data remains unreliable","data",4,5,"Remediate critical SKU and location master data before scale"),("Carrier event integration is delayed","vendor",3,4,"Contract milestone and fallback batch feed"),("Benefits overlap causes double counting","financial",3,4,"Finance-led benefit owner and overlap adjustment")]:db.add(Risk(engagement_id=e.id,description=desc,category=cat,likelihood=l,impact=i,overall_rating=l*i,mitigation=mit,contingency="Pause scale and return to pilot controls",owner="Transformation Director",review_date=date(2026,9,30),status="Open"))
    for n,r,i,t,c in [("Amelia Grant","COO",5,5,"Delivery disruption"),("Daniel Webb","CFO",5,4,"Benefit confidence"),("Priya Shah","Store Operations Director",4,5,"Implementation capacity"),("Store colleagues","Front line",2,5,"Workload and usability")]:db.add(Stakeholder(engagement_id=e.id,name=n,role=r,influence=i,interest=t,current_support=3,desired_support=5,concerns=c,engagement_approach="Evidence-led working sessions and visible issue resolution",communication_frequency="Fortnightly",classification="Manage Closely" if i>=4 and t>=4 else "Keep Informed"))
    for n,fn,vals,target in [("Operating margin","Finance",[8.6,8.1,7.7,7.1,6.6,6.0],8),("On-time delivery","Operations",[91,88,85,81,77,73],90),("Stock-out rate","Supply chain",[6.1,7.0,8.1,9.0,9.6,9.8],4),("Monthly complaints","Customer service",[820,880,950,1030,1110,1190],800)]:
        for idx,v in enumerate(vals):db.add(KPI(engagement_id=e.id,function=fn,name=n,period=f"2025-{idx+7:02d}",value=v,target=target,unit="%" if "rate" in n.lower() or "margin" in n.lower() or "delivery" in n.lower() else "cases",source="NorthStar sample dataset"))
    db.add(AuditEvent(engagement_id=e.id,action="seeded",resource_type="Engagement",resource_id=e.id,detail="Evidence-linked NorthStar demonstration engagement created"));db.commit();return e
